# Generated by Django 3.1 on 2020-09-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200908_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='clearance',
            field=models.BooleanField(default=False),
        ),
    ]
