# Generated by Django 3.1 on 2020-09-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_clearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='clearance',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
