# Generated by Django 3.1 on 2020-09-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200908_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='out_of_stock',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
