# Generated by Django 3.1 on 2020-09-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20200909_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='clearance',
            field=models.BooleanField(default=False),
        ),
    ]
