# Generated by Django 3.1 on 2020-09-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='default_county',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
